// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/environments": {
            "post": {
                "description": "基于ServiceAccount的kubeconfig创建完整的K8s环境，包括PVC、Deployment和Service。使用传入的kubeconfig中的身份信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "environments"
                ],
                "summary": "创建环境",
                "parameters": [
                    {
                        "description": "创建环境请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.CreateEnvironmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/main.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/main.APIResponse"
                        }
                    }
                }
            }
        },
        "/environments/{name}": {
            "get": {
                "description": "获取指定名称的环境的状态信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "environments"
                ],
                "summary": "获取环境信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "环境名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "获取环境信息请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.GetEnvironmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/main.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/main.APIResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除指定名称的环境，包括PVC、Deployment和Service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "environments"
                ],
                "summary": "删除环境",
                "parameters": [
                    {
                        "type": "string",
                        "description": "环境名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "删除环境请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.DeleteEnvironmentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/main.APIResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/main.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/main.APIResponse"
                        }
                    }
                }
            }
        },
        "/service-accounts": {
            "post": {
                "description": "创建指定的ServiceAccount，分配权限，并返回对应的kubeconfig",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-accounts"
                ],
                "summary": "创建ServiceAccount并返回kubeconfig",
                "parameters": [
                    {
                        "description": "创建ServiceAccount请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.KubeconfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/main.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/main.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/main.APIResponse"
                        }
                    }
                }
            }
        },
        "/service-accounts/{name}": {
            "delete": {
                "description": "删除指定的ServiceAccount及其相关权限配置（Role、RoleBinding、ResourceQuota）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "service-accounts"
                ],
                "summary": "删除ServiceAccount",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ServiceAccount名称",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "删除ServiceAccount请求参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.DeleteServiceAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功",
                        "schema": {
                            "$ref": "#/definitions/main.APIResponse"
                        }
                    },
                    "400": {
                        "description": "请求参数错误",
                        "schema": {
                            "$ref": "#/definitions/main.APIResponse"
                        }
                    },
                    "500": {
                        "description": "服务器内部错误",
                        "schema": {
                            "$ref": "#/definitions/main.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                }
            }
        },
        "main.CreateEnvironmentRequest": {
            "type": "object",
            "required": [
                "kubeconfig",
                "name",
                "nodeports",
                "resources",
                "storage"
            ],
            "properties": {
                "kubeconfig": {
                    "type": "string",
                    "example": "apiVersion: v1\nkind: Config\n..."
                },
                "name": {
                    "type": "string",
                    "example": "demo"
                },
                "namespace": {
                    "type": "string",
                    "example": "dev-space"
                },
                "nodeports": {
                    "type": "object",
                    "required": [
                        "ssh",
                        "terminal",
                        "vscode"
                    ],
                    "properties": {
                        "ssh": {
                            "type": "integer",
                            "example": 31496
                        },
                        "terminal": {
                            "type": "integer",
                            "example": 32259
                        },
                        "vscode": {
                            "type": "integer",
                            "example": 30582
                        }
                    }
                },
                "resources": {
                    "type": "object",
                    "required": [
                        "cpu",
                        "cpu_limit",
                        "memory",
                        "memory_limit"
                    ],
                    "properties": {
                        "cpu": {
                            "type": "string",
                            "example": "1000m"
                        },
                        "cpu_limit": {
                            "type": "string",
                            "example": "2000m"
                        },
                        "memory": {
                            "type": "string",
                            "example": "2Gi"
                        },
                        "memory_limit": {
                            "type": "string",
                            "example": "4Gi"
                        }
                    }
                },
                "storage": {
                    "type": "object",
                    "required": [
                        "vscode",
                        "workspace"
                    ],
                    "properties": {
                        "vscode": {
                            "type": "string",
                            "example": "5Gi"
                        },
                        "workspace": {
                            "type": "string",
                            "example": "10Gi"
                        }
                    }
                }
            }
        },
        "main.DeleteEnvironmentRequest": {
            "type": "object",
            "required": [
                "kubeconfig",
                "namespace"
            ],
            "properties": {
                "kubeconfig": {
                    "type": "string",
                    "example": "apiVersion: v1\nkind: Config\n..."
                },
                "namespace": {
                    "type": "string",
                    "example": "dev-space"
                }
            }
        },
        "main.DeleteServiceAccountRequest": {
            "type": "object",
            "required": [
                "kubeconfig",
                "namespace"
            ],
            "properties": {
                "kubeconfig": {
                    "type": "string",
                    "example": "apiVersion: v1\nkind: Config\n..."
                },
                "namespace": {
                    "type": "string",
                    "example": "dev-space"
                }
            }
        },
        "main.GetEnvironmentRequest": {
            "type": "object",
            "required": [
                "kubeconfig",
                "namespace"
            ],
            "properties": {
                "kubeconfig": {
                    "type": "string",
                    "example": "apiVersion: v1\nkind: Config\n..."
                },
                "namespace": {
                    "type": "string",
                    "example": "dev-space"
                }
            }
        },
        "main.KubeconfigRequest": {
            "type": "object",
            "required": [
                "kubeconfig",
                "sa_name"
            ],
            "properties": {
                "create_if_not_exists": {
                    "type": "boolean",
                    "example": true
                },
                "kubeconfig": {
                    "type": "string",
                    "example": "apiVersion: v1\nkind: Config\n..."
                },
                "namespace": {
                    "type": "string",
                    "example": "default"
                },
                "resource_limits": {
                    "type": "object",
                    "properties": {
                        "cpu": {
                            "type": "string",
                            "example": "8"
                        },
                        "memory": {
                            "type": "string",
                            "example": "16Gi"
                        },
                        "pod_count": {
                            "type": "string",
                            "example": "2"
                        },
                        "storage": {
                            "type": "string",
                            "example": "20Gi"
                        }
                    }
                },
                "sa_name": {
                    "type": "string",
                    "example": "dev-user"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1/k8s",
	Schemes:          []string{},
	Title:            "K8S Resource API",
	Description:      "Kubernetes资源管理API，支持动态创建开发环境和SA权限管理",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
